# Generated by Django 5.1.1 on 2024-10-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='contactno',
            field=models.IntegerField(max_length=100),
        ),
    ]
