# Generated by Django 5.1.1 on 2024-10-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_booking', '0002_alter_booking_contactno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='contactno',
            field=models.CharField(max_length=100),
        ),
    ]
